SUBJECT_VIDEO_CHANNELS = {
    "Mathematics": "Khan Academy The Organic Chemistry Tutor",
    "Physics": "Khan Academy Flipping Physics Physics Online",
    "Chemistry": "Khan Academy The Organic Chemistry Tutor Tyler DeWitt",
    "Biology": "Amoeba Sisters Khan Academy Crash Course Biology",
    "English": "BBC Learning English Khan Academy English",
    "Computer Science": "freeCodeCamp Programming with Mosh Khan Academy Computing",
}


TOPIC_PROFILES = {
    "Mathematics": {
        "Algebra": {
            "overview": "Algebra introduces variables, expressions, and equations so students can represent unknown values and solve problems systematically.",
            "focus": "forming expressions, simplifying terms, and solving equations with unknowns",
            "example": "translating a word problem into an equation and solving for the unknown",
            "mistake": "combining unlike terms or changing the sign incorrectly when moving terms",
            "practice": "simplifying expressions and solving linear equations step by step",
            "video_terms": "algebra basics variables expressions equations",
        },
        "Geometry": {
            "overview": "Geometry studies shapes, angles, lines, and spatial relationships so students can reason about figures and measurements.",
            "focus": "properties of shapes, angle rules, and relationships between lines",
            "example": "finding a missing angle in a triangle or parallel-line diagram",
            "mistake": "using the wrong angle rule or confusing different shapes",
            "practice": "identifying shapes, angle facts, and perimeter or area tasks",
            "video_terms": "geometry lines angles shapes basics",
        },
        "Trigonometry": {
            "overview": "Trigonometry connects angles and side lengths in triangles using ratios such as sine, cosine, and tangent.",
            "focus": "right-triangle ratios and deciding which trig ratio fits a question",
            "example": "finding the height of a building using angle of elevation",
            "mistake": "choosing the wrong ratio or mixing degrees with calculator settings",
            "practice": "finding missing sides or angles in right triangles",
            "video_terms": "trigonometry sine cosine tangent right triangle",
        },
        "Calculus": {
            "overview": "Calculus examines change and accumulation, especially through differentiation and integration.",
            "focus": "rates of change, gradients, and accumulated quantities",
            "example": "finding how fast a quantity changes at a point on a graph",
            "mistake": "applying a rule mechanically without understanding what the derivative or integral means",
            "practice": "basic derivative and area-under-curve reasoning",
            "video_terms": "calculus introduction derivatives integrals",
        },
        "Statistics": {
            "overview": "Statistics helps students collect, summarize, and interpret data clearly.",
            "focus": "measures of central tendency, spread, and data representation",
            "example": "comparing two data sets using mean and range",
            "mistake": "using the wrong average or ignoring outliers",
            "practice": "reading charts and calculating mean, median, mode, and range",
            "video_terms": "statistics mean median mode range data",
        },
        "Probability": {
            "overview": "Probability measures how likely events are and helps students reason about chance.",
            "focus": "sample spaces, favorable outcomes, and probability rules",
            "example": "finding the probability of drawing a particular card or rolling a number",
            "mistake": "counting outcomes incorrectly or forgetting total outcomes",
            "practice": "simple events, combined events, and complements",
            "video_terms": "probability basics sample space events",
        },
        "Vectors": {
            "overview": "Vectors describe quantities with both magnitude and direction.",
            "focus": "representing directed quantities and performing vector operations",
            "example": "combining two displacements to find a resultant vector",
            "mistake": "treating vectors like ordinary numbers without direction",
            "practice": "vector addition, subtraction, and components",
            "video_terms": "vectors magnitude direction components",
        },
        "Matrices": {
            "overview": "Matrices organize numbers in rows and columns for transformations, systems, and calculations.",
            "focus": "matrix notation, operations, and interpreting entries correctly",
            "example": "adding matrices or multiplying a matrix by a scalar",
            "mistake": "using the wrong order when multiplying or mismatching dimensions",
            "practice": "basic matrix operations and simple transformations",
            "video_terms": "matrices introduction operations rows columns",
        },
        "Number Theory": {
            "overview": "Number theory studies the structure and properties of whole numbers.",
            "focus": "factors, multiples, primes, divisibility, and remainders",
            "example": "using prime factorization to find HCF or LCM",
            "mistake": "confusing prime numbers with odd numbers or misusing factor rules",
            "practice": "divisibility tests and factor-based reasoning",
            "video_terms": "number theory factors multiples primes divisibility",
        },
        "Differentiation": {
            "overview": "Differentiation finds the rate at which one quantity changes with respect to another.",
            "focus": "derivative rules and interpreting gradient",
            "example": "finding the derivative of a polynomial and using it as slope",
            "mistake": "forgetting to reduce the power correctly or mishandling constants",
            "practice": "power rule and tangent-gradient questions",
            "video_terms": "differentiation power rule gradient",
        },
        "Integration": {
            "overview": "Integration is used to find accumulated quantities and reverse differentiation.",
            "focus": "anti-derivatives and area ideas",
            "example": "integrating a simple polynomial expression",
            "mistake": "forgetting the constant of integration or increasing powers incorrectly",
            "practice": "basic indefinite integrals and area interpretation",
            "video_terms": "integration anti derivative basics",
        },
        "Quadratic Equations": {
            "overview": "Quadratic equations involve squared terms and can be solved by factorization, formula, or completing the square.",
            "focus": "recognizing quadratic form and selecting a suitable solving method",
            "example": "solving a quadratic by factorization and checking the roots",
            "mistake": "sign errors while factorizing or misusing the quadratic formula",
            "practice": "solving and interpreting roots of quadratics",
            "video_terms": "quadratic equations factorization formula",
        },
        "Indices": {
            "overview": "Indices describe repeated multiplication and lead to important laws of exponents.",
            "focus": "laws of indices for multiplication, division, powers, and roots",
            "example": "simplifying an expression with positive and negative indices",
            "mistake": "adding exponents when division is required or mishandling zero powers",
            "practice": "simplifying exponential expressions",
            "video_terms": "indices exponents laws of indices",
        },
        "Logarithms": {
            "overview": "Logarithms are the inverse of exponents and help solve exponential relationships.",
            "focus": "log laws and converting between exponential and logarithmic form",
            "example": "expanding or simplifying a logarithmic expression",
            "mistake": "applying log laws as if logs distribute over sums incorrectly",
            "practice": "basic log laws and equation solving",
            "video_terms": "logarithms laws introduction",
        },
        "Sets": {
            "overview": "Sets group objects clearly and help students reason about membership and relationships.",
            "focus": "union, intersection, subsets, and Venn diagrams",
            "example": "using a Venn diagram to count elements in overlapping groups",
            "mistake": "confusing intersection with union or miscounting overlaps",
            "practice": "set notation and Venn-diagram questions",
            "video_terms": "sets union intersection venn diagram",
        },
        "Functions": {
            "overview": "Functions show how each input is linked to exactly one output.",
            "focus": "input-output relationships, notation, and evaluation",
            "example": "finding the value of f(x) for a given input",
            "mistake": "mixing up variables or not substituting correctly",
            "practice": "evaluating and interpreting simple functions",
            "video_terms": "functions notation input output",
        },
        "Graphs": {
            "overview": "Graphs turn equations and data into visual relationships that students can interpret.",
            "focus": "plotting points, reading gradients, and identifying intercepts",
            "example": "drawing a straight-line graph from a table of values",
            "mistake": "using the wrong scale or plotting coordinates in reverse order",
            "practice": "plotting and interpreting linear graphs",
            "video_terms": "graphs plotting coordinates slope intercept",
        },
        "Sequences": {
            "overview": "Sequences are ordered lists that follow a pattern or rule from one term to the next.",
            "focus": "term patterns, nth-term rules, and arithmetic thinking",
            "example": "finding the next terms and deriving the nth term of a sequence",
            "mistake": "assuming the pattern without checking how terms actually change",
            "practice": "arithmetic and simple pattern sequences",
            "video_terms": "sequences nth term arithmetic sequence",
        },
        "Series": {
            "overview": "A series adds the terms of a sequence and helps students reason about totals built from patterns.",
            "focus": "partial sums and formulas for adding patterned terms",
            "example": "finding the sum of the first n terms of an arithmetic series",
            "mistake": "using sequence formulas instead of series formulas",
            "practice": "sum of arithmetic series questions",
            "video_terms": "series sums arithmetic series",
        },
        "Mensuration": {
            "overview": "Mensuration deals with measuring length, area, surface area, and volume of shapes.",
            "focus": "choosing the correct measurement formula for a shape",
            "example": "finding the volume of a cylinder or the area of a compound shape",
            "mistake": "using the wrong units or confusing area with volume",
            "practice": "perimeter, area, and volume calculations",
            "video_terms": "mensuration area volume perimeter",
        },
    },
    "Physics": {
        "Motion": {"overview": "Motion explains how objects change position with time.", "focus": "distance, displacement, speed, and velocity", "example": "comparing two journeys using distance and displacement", "mistake": "treating speed and velocity as the same quantity", "practice": "distance-time and velocity reasoning", "video_terms": "motion distance displacement speed velocity"},
        "Force": {"overview": "Force causes changes in motion and helps explain pushes, pulls, and interactions.", "focus": "balanced and unbalanced forces and Newton's ideas", "example": "explaining why an object starts moving or stops", "mistake": "assuming motion always needs a continuing force", "practice": "net force and simple force diagrams", "video_terms": "force basics net force newton laws"},
        "Energy": {"overview": "Energy describes the ability to do work and appears in many forms.", "focus": "energy forms and transfer between systems", "example": "tracing energy changes in a moving car or falling ball", "mistake": "listing energy forms without explaining how transfer happens", "practice": "energy conversion questions", "video_terms": "energy forms transfer conservation"},
        "Power": {"overview": "Power measures how quickly work is done or energy is transferred.", "focus": "rate of doing work and interpreting the power formula", "example": "comparing two machines that do the same work in different times", "mistake": "confusing power with energy", "practice": "power calculations using work and time", "video_terms": "power physics work time"},
        "Work": {"overview": "Work is done when a force moves an object through a distance.", "focus": "force-distance relationship and units of work", "example": "calculating work done when lifting an object", "mistake": "saying work is done even when there is no movement", "practice": "work done formula questions", "video_terms": "work done force distance"},
        "Momentum": {"overview": "Momentum links mass and velocity and helps explain collisions.", "focus": "quantity of motion and conservation ideas", "example": "comparing the momentum of moving objects before and after impact", "mistake": "mixing up momentum and force", "practice": "momentum calculations and collision reasoning", "video_terms": "momentum conservation collisions"},
        "Electricity": {"overview": "Electricity studies charge, current flow, and how circuits work.", "focus": "basic circuit ideas and electrical quantities", "example": "describing what happens in a simple series circuit", "mistake": "thinking current gets used up in a circuit", "practice": "current, voltage, and simple circuits", "video_terms": "electricity circuits current voltage"},
        "Magnetism": {"overview": "Magnetism explains forces around magnets and magnetic fields.", "focus": "magnetic poles, fields, and attraction-repulsion", "example": "predicting what happens when different poles are brought together", "mistake": "confusing magnetic effects with electric charge", "practice": "field lines and magnet interactions", "video_terms": "magnetism magnetic field poles"},
        "Waves": {"overview": "Waves transfer energy through vibrations without transferring matter overall.", "focus": "wave properties such as wavelength, frequency, and amplitude", "example": "reading wave features from a diagram", "mistake": "confusing amplitude with wavelength", "practice": "wave terms and calculations", "video_terms": "waves wavelength frequency amplitude"},
        "Optics": {"overview": "Optics studies light, reflection, refraction, and image formation.", "focus": "how light behaves with mirrors and lenses", "example": "drawing a ray diagram for a convex lens", "mistake": "placing images on the wrong side or drawing incorrect rays", "practice": "reflection, refraction, and lenses", "video_terms": "optics reflection refraction lenses"},
        "Heat": {"overview": "Heat deals with thermal energy transfer and temperature change.", "focus": "conduction, convection, radiation, and heat flow", "example": "explaining how a metal spoon gets hot in tea", "mistake": "treating heat and temperature as identical", "practice": "methods of heat transfer", "video_terms": "heat transfer conduction convection radiation"},
        "Pressure": {"overview": "Pressure measures force spread over an area.", "focus": "how contact area changes pressure in solids and fluids", "example": "explaining why sharp objects create higher pressure", "mistake": "forgetting that smaller area increases pressure", "practice": "pressure formula and applications", "video_terms": "pressure force area fluids"},
        "Nuclear Physics": {"overview": "Nuclear physics studies the atom's nucleus, radioactivity, and nuclear changes.", "focus": "decay, radiation types, and nuclear stability", "example": "comparing alpha, beta, and gamma radiation", "mistake": "confusing nuclear changes with chemical reactions", "practice": "radioactivity and decay questions", "video_terms": "nuclear physics radioactivity alpha beta gamma"},
        "Electronics": {"overview": "Electronics examines components and circuits used to control electric signals.", "focus": "diodes, resistors, transistors, and simple logic functions", "example": "explaining the role of a diode in a circuit", "mistake": "naming components without explaining what they do", "practice": "component symbols and circuit uses", "video_terms": "electronics basic components circuits"},
        "Current": {"overview": "Current describes the rate of flow of electric charge.", "focus": "charge flow, units, and measuring current", "example": "explaining current in a series circuit", "mistake": "thinking current is stored in one component", "practice": "current calculations and circuit readings", "video_terms": "current electricity charge flow"},
        "Voltage": {"overview": "Voltage is the electrical potential difference that drives charge through a circuit.", "focus": "potential difference and energy per unit charge", "example": "comparing battery voltages in simple circuits", "mistake": "confusing voltage with current", "practice": "potential-difference reasoning", "video_terms": "voltage potential difference circuits"},
        "Resistance": {"overview": "Resistance describes how much a material or component opposes current flow.", "focus": "opposition to current and factors affecting resistance", "example": "why a thin wire may have more resistance than a thick one", "mistake": "assuming all materials conduct equally", "practice": "Ohm's law and resistance changes", "video_terms": "resistance ohms law"},
        "Gravity": {"overview": "Gravity is the attractive force between masses and explains weight and falling motion.", "focus": "gravitational attraction, mass, and weight", "example": "distinguishing between mass and weight on Earth", "mistake": "using mass and weight as interchangeable terms", "practice": "weight calculations and gravity concepts", "video_terms": "gravity mass weight"},
        "Projectile Motion": {"overview": "Projectile motion combines horizontal and vertical motion under gravity.", "focus": "independent motion components and curved paths", "example": "describing the path of a ball thrown at an angle", "mistake": "thinking the horizontal motion stops because gravity acts downward", "practice": "trajectory interpretation", "video_terms": "projectile motion horizontal vertical"},
        "Sound": {"overview": "Sound is a wave produced by vibrations and transmitted through media.", "focus": "vibration, wave transmission, and pitch-loudness ideas", "example": "explaining why changing string tension affects pitch", "mistake": "mixing up pitch and loudness", "practice": "sound production and wave behavior", "video_terms": "sound waves pitch loudness"},
    },
    "Chemistry": {
        "Atomic Structure": {"overview": "Atomic structure explains how protons, neutrons, and electrons make up atoms.", "focus": "particle arrangement and how atomic number defines an element", "example": "describing the structure of sodium or oxygen", "mistake": "confusing mass number with atomic number", "practice": "counting subatomic particles", "video_terms": "atomic structure protons neutrons electrons"},
        "Periodic Table": {"overview": "The periodic table organizes elements by atomic number and recurring chemical properties.", "focus": "groups, periods, and trends across the table", "example": "predicting the behavior of an element from its group", "mistake": "memorizing positions without linking them to properties", "practice": "group and period interpretation", "video_terms": "periodic table groups periods properties"},
        "Chemical Bonding": {"overview": "Chemical bonding explains how atoms combine through ionic, covalent, or metallic bonds.", "focus": "why atoms bond and what each bond type looks like", "example": "comparing sodium chloride and water bonding", "mistake": "mixing ionic transfer with covalent sharing", "practice": "identifying bond types and properties", "video_terms": "chemical bonding ionic covalent metallic"},
        "Organic Chemistry": {"overview": "Organic chemistry studies carbon compounds and their structures, reactions, and uses.", "focus": "carbon chains, functional groups, and common reactions", "example": "describing the structure of an alkane or alcohol", "mistake": "ignoring the role of functional groups", "practice": "naming and identifying organic compounds", "video_terms": "organic chemistry basics hydrocarbons functional groups"},
        "Hydrocarbons": {"overview": "Hydrocarbons are compounds made only of hydrogen and carbon.", "focus": "alkanes, alkenes, and how structure affects behavior", "example": "comparing saturated and unsaturated hydrocarbons", "mistake": "confusing alkanes with alkenes", "practice": "classification and simple reactions of hydrocarbons", "video_terms": "hydrocarbons alkanes alkenes"},
        "Acids": {"overview": "Acids are substances that release hydrogen ions in solution and have characteristic reactions.", "focus": "properties of acids and reactions with metals, bases, and carbonates", "example": "predicting products when an acid reacts with a metal", "mistake": "treating all corrosive substances as acids", "practice": "acid reactions and indicators", "video_terms": "acids reactions indicators chemistry"},
        "Bases": {"overview": "Bases and alkalis react with acids and are important in neutralization.", "focus": "basic properties, pH, and reactions with acids", "example": "explaining how sodium hydroxide neutralizes an acid", "mistake": "assuming every base is soluble in water", "practice": "base properties and neutralization", "video_terms": "bases alkalis neutralization"},
        "Salts": {"overview": "Salts are ionic compounds often formed during neutralization or other reactions.", "focus": "methods of salt formation and identifying ions", "example": "preparing a salt from an acid-base reaction", "mistake": "calling every white solid a salt without checking composition", "practice": "forming and naming salts", "video_terms": "salts formation naming chemistry"},
        "Electrolysis": {"overview": "Electrolysis uses electricity to decompose ionic substances.", "focus": "movement of ions and products at the electrodes", "example": "predicting products from electrolysis of copper sulfate", "mistake": "mixing up anode and cathode products", "practice": "electrode reactions and observations", "video_terms": "electrolysis anode cathode ions"},
        "Equilibrium": {"overview": "Chemical equilibrium describes reversible reactions where forward and reverse rates balance.", "focus": "dynamic balance and factors that shift equilibrium", "example": "explaining what happens when concentration changes", "mistake": "thinking equilibrium means the reaction has stopped", "practice": "Le Chatelier style reasoning", "video_terms": "chemical equilibrium reversible reactions"},
        "Reaction Rates": {"overview": "Reaction rates show how fast chemical changes happen.", "focus": "collision theory and factors affecting reaction speed", "example": "explaining why powdered solids react faster than lumps", "mistake": "listing factors without linking them to particle collisions", "practice": "temperature, surface area, catalyst effects", "video_terms": "rate of reaction collision theory"},
        "Thermochemistry": {"overview": "Thermochemistry studies heat changes during chemical reactions.", "focus": "exothermic and endothermic processes and energy diagrams", "example": "comparing heat flow in combustion and decomposition", "mistake": "confusing heat released with temperature alone", "practice": "identifying and interpreting energy changes", "video_terms": "thermochemistry exothermic endothermic"},
        "Redox": {"overview": "Redox reactions involve oxidation and reduction happening together.", "focus": "electron transfer and oxidation number changes", "example": "identifying what is oxidized and reduced in a reaction", "mistake": "memorizing OIL RIG without applying it carefully", "practice": "oxidation numbers and redox identification", "video_terms": "redox oxidation reduction electrons"},
        "Gas Laws": {"overview": "Gas laws connect pressure, volume, and temperature in gases.", "focus": "relationships between gas variables and interpreting experiments", "example": "explaining what happens to gas volume when temperature rises", "mistake": "mixing up direct and inverse relationships", "practice": "Boyle's and Charles' law reasoning", "video_terms": "gas laws pressure volume temperature"},
        "Stoichiometry": {"overview": "Stoichiometry uses balanced equations to calculate reacting masses and amounts.", "focus": "mole ratios and converting between quantities", "example": "calculating the mass of product from a known reactant amount", "mistake": "using unbalanced equations or wrong mole ratios", "practice": "mole conversions and mass calculations", "video_terms": "stoichiometry moles balanced equations"},
        "Solutions": {"overview": "Solutions are homogeneous mixtures formed when solutes dissolve in solvents.", "focus": "solubility, concentration, and preparation of solutions", "example": "calculating concentration from mass and volume", "mistake": "confusing dilution with dissolving more solute", "practice": "concentration and dilution questions", "video_terms": "solutions concentration solubility"},
        "Metals": {"overview": "Metals have characteristic physical and chemical properties linked to their structure.", "focus": "conductivity, malleability, reactivity, and uses", "example": "comparing the reactivity of magnesium and copper", "mistake": "describing every shiny material as a metal", "practice": "metal properties and reactions", "video_terms": "metals properties reactivity"},
        "Non-metals": {"overview": "Non-metals differ from metals in bonding, conductivity, and physical behavior.", "focus": "contrasting non-metal properties and common examples", "example": "explaining why sulfur and oxygen behave differently from metals", "mistake": "assuming non-metals cannot react strongly", "practice": "property comparisons and uses", "video_terms": "non metals properties chemistry"},
        "Polymers": {"overview": "Polymers are large molecules made from repeating smaller units called monomers.", "focus": "polymer formation and useful material properties", "example": "describing addition polymerization from an alkene", "mistake": "confusing monomer with polymer", "practice": "polymer structure and everyday applications", "video_terms": "polymers monomers polymerization"},
        "Water": {"overview": "Water is a vital substance with unique physical and chemical properties.", "focus": "composition, purification, hardness, and environmental importance", "example": "explaining why water is used as a solvent", "mistake": "treating natural water as always chemically pure", "practice": "water treatment and properties", "video_terms": "water chemistry purification hardness"},
    },
    "Biology": {
        "Cell": {"overview": "Cells are the basic structural and functional units of living things.", "focus": "organelles and how cell parts work together", "example": "comparing plant and animal cells", "mistake": "naming organelles without explaining their jobs", "practice": "cell structure and function questions", "video_terms": "cell biology organelles plant animal"},
        "Genetics": {"overview": "Genetics explains how traits are inherited from parents to offspring.", "focus": "genes, alleles, and inheritance patterns", "example": "using a Punnett square for a simple trait", "mistake": "confusing genotype with phenotype", "practice": "inheritance and trait prediction", "video_terms": "genetics genes alleles punnett square"},
        "Ecology": {"overview": "Ecology studies how organisms interact with one another and their environment.", "focus": "ecosystems, food chains, and environmental balance", "example": "showing how a change in one species affects others", "mistake": "treating organisms as if they live independently of habitat", "practice": "ecosystem and population questions", "video_terms": "ecology ecosystem food chain"},
        "Evolution": {"overview": "Evolution explains how populations change over time through inherited variation and selection.", "focus": "adaptation, variation, and natural selection", "example": "explaining how a useful trait becomes common", "mistake": "thinking individuals evolve during their lifetime", "practice": "adaptation and selection reasoning", "video_terms": "evolution natural selection adaptation"},
        "Photosynthesis": {"overview": "Photosynthesis allows green plants to make food using sunlight, water, and carbon dioxide.", "focus": "raw materials, products, and why the process matters", "example": "describing how a leaf makes glucose", "mistake": "confusing photosynthesis with respiration", "practice": "equation and process conditions", "video_terms": "photosynthesis process chlorophyll glucose"},
        "Respiration": {"overview": "Respiration releases energy from food for life processes.", "focus": "aerobic respiration and the need for energy in cells", "example": "linking breathing and energy release in active muscles", "mistake": "treating respiration as the same thing as breathing", "practice": "respiration equation and comparisons", "video_terms": "respiration aerobic anaerobic biology"},
        "Nutrition": {"overview": "Nutrition examines how organisms obtain and use food for growth and health.", "focus": "balanced diet, nutrients, and food functions", "example": "explaining why proteins and carbohydrates play different roles", "mistake": "calling every food nutrient an energy source", "practice": "diet and nutrient-function questions", "video_terms": "nutrition balanced diet nutrients"},
        "Excretion": {"overview": "Excretion removes metabolic waste products from the body.", "focus": "waste products, organs involved, and homeostasis", "example": "describing how the kidneys remove urea", "mistake": "mixing excretion up with egestion", "practice": "excretory organs and waste removal", "video_terms": "excretion kidneys urea homeostasis"},
        "Circulatory System": {"overview": "The circulatory system transports oxygen, nutrients, hormones, and wastes around the body.", "focus": "heart structure, blood vessels, and circulation pathways", "example": "tracing blood through the heart and lungs", "mistake": "mixing arteries and veins or oxygenated and deoxygenated blood", "practice": "blood flow and heart-function questions", "video_terms": "circulatory system heart blood vessels"},
        "Digestive System": {"overview": "The digestive system breaks food down and absorbs useful nutrients.", "focus": "organs, digestion stages, and absorption", "example": "following food from mouth to small intestine", "mistake": "confusing digestion with absorption", "practice": "digestive organs and enzyme roles", "video_terms": "digestive system digestion absorption"},
        "Nervous System": {"overview": "The nervous system detects stimuli and coordinates responses quickly.", "focus": "neurons, brain, spinal cord, and reflex actions", "example": "explaining a reflex arc", "mistake": "assuming all responses require conscious thinking", "practice": "neuron function and reflex questions", "video_terms": "nervous system neurons reflex arc"},
        "Hormones": {"overview": "Hormones are chemical messengers that control body processes more slowly than nerves.", "focus": "endocrine glands, targets, and regulation", "example": "describing how insulin affects blood sugar", "mistake": "mixing hormonal control with nervous control", "practice": "glands and hormone-function questions", "video_terms": "hormones endocrine glands insulin"},
        "Reproduction": {"overview": "Reproduction ensures the continuation of species.", "focus": "sexual reproduction, fertilization, and development", "example": "comparing male and female reproductive roles", "mistake": "mixing fertilization with implantation or growth stages", "practice": "reproductive structures and processes", "video_terms": "reproduction fertilization human biology"},
        "Classification": {"overview": "Classification groups organisms based on shared features and relationships.", "focus": "taxonomic levels and reasons for grouping organisms", "example": "placing an organism into the correct kingdom or class", "mistake": "grouping by one obvious feature only", "practice": "taxonomy and organism comparison", "video_terms": "classification taxonomy kingdoms"},
        "Microorganisms": {"overview": "Microorganisms are tiny living things that can be useful or harmful.", "focus": "types of microbes and their effects", "example": "comparing bacteria, fungi, and viruses", "mistake": "assuming all microbes cause disease", "practice": "microbe roles and infection basics", "video_terms": "microorganisms bacteria fungi viruses"},
        "Immunity": {"overview": "Immunity protects the body against disease-causing organisms.", "focus": "body defenses, antibodies, and vaccination", "example": "explaining how a vaccine prepares the immune system", "mistake": "thinking antibiotics work against viruses", "practice": "immune response and vaccination", "video_terms": "immunity antibodies vaccines"},
        "Plants": {"overview": "Plant biology studies the structure and life processes of plants.", "focus": "roots, stems, leaves, transport, and growth", "example": "explaining how water moves through a plant", "mistake": "describing plants as passive without active processes", "practice": "plant structure-function questions", "video_terms": "plants biology transport transpiration"},
        "Animals": {"overview": "Animal biology studies animal structure, behavior, and adaptation.", "focus": "body systems, movement, feeding, and adaptation", "example": "comparing herbivores and carnivores", "mistake": "generalizing one animal system to all species", "practice": "adaptation and body-system questions", "video_terms": "animals adaptations biology"},
        "DNA": {"overview": "DNA carries genetic information used to build and control living organisms.", "focus": "double helix, genes, and coded instructions", "example": "linking DNA to inherited traits", "mistake": "treating DNA, genes, and chromosomes as exactly the same thing", "practice": "DNA structure and inheritance links", "video_terms": "DNA genes chromosomes biology"},
        "Protein Synthesis": {"overview": "Protein synthesis explains how genetic information is used to build proteins.", "focus": "transcription, translation, and the role of ribosomes", "example": "following how a DNA code leads to a protein", "mistake": "mixing DNA and RNA roles", "practice": "gene expression sequence questions", "video_terms": "protein synthesis transcription translation"},
    },
    "English": {
        "Grammar": {"overview": "Grammar gives structure to language so ideas are clear, accurate, and meaningful.", "focus": "sentence structure, agreement, and correct usage", "example": "editing a sentence to fix tense or agreement errors", "mistake": "writing sentences that sound natural but break grammar rules", "practice": "error correction and sentence building", "video_terms": "grammar basics sentence structure"},
        "Comprehension": {"overview": "Comprehension helps students understand, interpret, and respond to texts accurately.", "focus": "finding key ideas, evidence, and implied meaning", "example": "answering questions from a short passage using textual evidence", "mistake": "copying lines without showing understanding", "practice": "reading passages and evidence-based responses", "video_terms": "reading comprehension strategies"},
        "Vocabulary": {"overview": "Vocabulary study expands word knowledge and improves precision in speaking and writing.", "focus": "word meaning, usage, and context clues", "example": "using context to infer the meaning of an unfamiliar word", "mistake": "memorizing definitions without learning usage", "practice": "context clues and word application", "video_terms": "english vocabulary context clues"},
        "Essay Writing": {"overview": "Essay writing organizes ideas into a clear introduction, body, and conclusion.", "focus": "planning, coherence, paragraph development, and support", "example": "building a paragraph with a topic sentence and supporting points", "mistake": "listing ideas without linking them logically", "practice": "paragraph and full-essay structure", "video_terms": "essay writing structure english"},
        "Letter Writing": {"overview": "Letter writing teaches purpose, format, tone, and audience awareness.", "focus": "formal and informal structures and suitable language", "example": "writing a formal request letter with proper layout", "mistake": "mixing formal tone with casual expressions", "practice": "formal and informal letter tasks", "video_terms": "letter writing formal informal"},
        "Tenses": {"overview": "Tenses show the time of actions and help students write accurately.", "focus": "past, present, future, and consistent verb forms", "example": "changing a paragraph from present tense to past tense", "mistake": "shifting tense halfway through a sentence or paragraph", "practice": "verb-form and tense-consistency exercises", "video_terms": "english tenses verb forms"},
        "Parts of Speech": {"overview": "Parts of speech classify words by their roles in sentences.", "focus": "nouns, verbs, adjectives, adverbs, and other word classes", "example": "identifying the function of a word within a sentence", "mistake": "classifying a word without checking how it is used", "practice": "sentence analysis by word class", "video_terms": "parts of speech nouns verbs adjectives"},
        "Figures of Speech": {"overview": "Figures of speech create imagery, emphasis, and style in language.", "focus": "metaphor, simile, personification, hyperbole, and effect", "example": "explaining the effect of a metaphor in a sentence", "mistake": "spotting a figure of speech without describing its effect", "practice": "identification and interpretation", "video_terms": "figures of speech metaphor simile"},
        "Summary": {"overview": "Summary writing condenses a text into its essential points without unnecessary detail.", "focus": "main ideas, concise expression, and omission of repetition", "example": "reducing a passage into a few clear sentences", "mistake": "copying large parts of the original text", "practice": "shortening passages into key points", "video_terms": "summary writing main ideas"},
        "Poetry": {"overview": "Poetry studies language, sound, imagery, and feeling in condensed form.", "focus": "theme, imagery, sound devices, and interpretation", "example": "explaining how a poet uses imagery to create mood", "mistake": "retelling the poem without analyzing techniques", "practice": "poem interpretation and device spotting", "video_terms": "poetry analysis imagery theme"},
        "Drama": {"overview": "Drama explores characters, dialogue, conflict, and stage presentation.", "focus": "plot, characterization, and dramatic effect", "example": "analyzing a scene's conflict and its effect on the audience", "mistake": "treating dialogue as plain narration", "practice": "character and scene analysis", "video_terms": "drama literary analysis"},
        "Novel": {"overview": "Novel study develops understanding of plot, character, setting, and theme in long prose texts.", "focus": "story development and critical interpretation", "example": "tracking how a character changes across chapters", "mistake": "telling the story without analyzing its meaning", "practice": "theme, plot, and character questions", "video_terms": "novel analysis character theme"},
        "Concord": {"overview": "Concord ensures agreement between subjects, verbs, pronouns, and related sentence parts.", "focus": "subject-verb agreement and consistency in structure", "example": "correcting a sentence where subject and verb do not match", "mistake": "being distracted by nearby words instead of the true subject", "practice": "agreement correction exercises", "video_terms": "concord subject verb agreement"},
        "Direct Speech": {"overview": "Direct speech reports exact spoken words using quotation marks.", "focus": "quotation punctuation and reporting exact words", "example": "writing a conversation using direct speech correctly", "mistake": "forgetting punctuation or quotation marks", "practice": "punctuating direct speech", "video_terms": "direct speech punctuation"},
        "Indirect Speech": {"overview": "Indirect speech reports what was said without repeating the exact words.", "focus": "reported-speech changes in tense, pronouns, and time words", "example": "changing a direct sentence into reported speech", "mistake": "keeping original tense and pronouns unchanged", "practice": "reported speech transformations", "video_terms": "indirect speech reported speech"},
        "Pronunciation": {"overview": "Pronunciation improves how words and sounds are spoken clearly.", "focus": "stress, vowel sounds, consonants, and clear articulation", "example": "contrasting minimal pairs with different vowel sounds", "mistake": "pronouncing words only by spelling", "practice": "stress patterns and sound distinctions", "video_terms": "pronunciation stress vowel sounds"},
        "Reading": {"overview": "Reading builds fluency, understanding, and critical response to texts.", "focus": "speed, accuracy, inference, and engagement with meaning", "example": "reading a text and identifying both explicit and implied meaning", "mistake": "moving too quickly without processing meaning", "practice": "guided reading and response tasks", "video_terms": "reading strategies english"},
        "Listening": {"overview": "Listening develops attention, interpretation, and response to spoken language.", "focus": "main points, details, tone, and speaker intention", "example": "extracting key points from an oral presentation", "mistake": "hearing words without organizing the ideas", "practice": "listening for gist and details", "video_terms": "listening skills english"},
        "Writing": {"overview": "Writing develops clear communication through planning, drafting, and revising.", "focus": "clarity, organization, sentence control, and audience awareness", "example": "turning rough notes into a coherent paragraph", "mistake": "writing without planning or revising", "practice": "guided composition and editing", "video_terms": "writing skills paragraph composition"},
        "Speaking": {"overview": "Speaking builds confidence, fluency, and accuracy in oral communication.", "focus": "clarity, tone, structure, and audience engagement", "example": "presenting a short opinion with supporting reasons", "mistake": "speaking without structure or clear transitions", "practice": "short presentations and oral responses", "video_terms": "speaking skills communication english"},
    },
    "Computer Science": {
        "Computer Basics": {"overview": "Computer basics introduce the major parts of a computer and what each part does.", "focus": "hardware, software, input, processing, storage, and output", "example": "tracing how data enters, is processed, and is displayed", "mistake": "mixing hardware devices with software programs", "practice": "identifying system components and their functions", "video_terms": "computer basics hardware software input output"},
        "Programming": {"overview": "Programming teaches students how to give computers step-by-step instructions to solve problems.", "focus": "algorithms, logic, sequence, selection, and repetition", "example": "writing a simple program that makes decisions", "mistake": "coding without first planning the logic", "practice": "basic algorithm and control-structure questions", "video_terms": "programming basics logic algorithms"},
        "Python": {"overview": "Python is a beginner-friendly programming language used for scripting, automation, and problem solving.", "focus": "syntax, variables, control flow, and functions in Python", "example": "writing a Python program that takes input and prints a result", "mistake": "forgetting indentation or mixing data types carelessly", "practice": "simple Python scripts and debugging", "video_terms": "python basics variables loops functions"},
        "Java": {"overview": "Java is a structured object-oriented programming language used in many applications.", "focus": "classes, methods, syntax, and program structure", "example": "creating a simple Java class with a method", "mistake": "confusing Java syntax with other languages or omitting required structure", "practice": "basic Java classes and methods", "video_terms": "java basics classes methods"},
        "C++": {"overview": "C++ is a powerful programming language used for systems and high-performance software.", "focus": "variables, functions, data types, and program compilation", "example": "writing and compiling a simple console program", "mistake": "ignoring semicolons, headers, or data-type rules", "practice": "basic C++ syntax and logic", "video_terms": "c++ basics variables functions"},
        "HTML": {"overview": "HTML structures content on web pages using tags and elements.", "focus": "headings, paragraphs, links, images, and semantic layout", "example": "building a simple page with sections and links", "mistake": "using tags without closing or nesting them properly", "practice": "basic webpage structure tasks", "video_terms": "html basics tags webpage"},
        "CSS": {"overview": "CSS controls the appearance and layout of web pages.", "focus": "selectors, properties, spacing, colors, and layout", "example": "styling a page with classes and simple layout rules", "mistake": "targeting the wrong element or mixing up property names", "practice": "basic styling and layout exercises", "video_terms": "css basics selectors layout"},
        "JavaScript": {"overview": "JavaScript adds interactivity and logic to web pages.", "focus": "variables, functions, events, and DOM updates", "example": "making a button change text on a page", "mistake": "mixing string and number operations or using the wrong selector", "practice": "simple interactive webpage tasks", "video_terms": "javascript basics dom events"},
        "Database": {"overview": "Databases organize, store, and retrieve information efficiently.", "focus": "tables, records, fields, and data relationships", "example": "designing a table for student information", "mistake": "storing unrelated data in one table without structure", "practice": "table design and data-management questions", "video_terms": "database basics tables records"},
        "SQL": {"overview": "SQL is used to query and manage data in relational databases.", "focus": "SELECT, INSERT, UPDATE, DELETE, and filtering data", "example": "writing a query to retrieve students with a certain score", "mistake": "forgetting conditions or selecting the wrong field", "practice": "basic query writing", "video_terms": "sql basics select where query"},
        "Networking": {"overview": "Networking connects computers so they can share data and resources.", "focus": "network types, devices, and communication basics", "example": "explaining how computers connect through a router", "mistake": "confusing the internet with a local network", "practice": "network device and topology questions", "video_terms": "networking basics routers protocols"},
        "Cybersecurity": {"overview": "Cybersecurity protects systems, data, and users from digital threats.", "focus": "passwords, malware, phishing, and safe practices", "example": "identifying a phishing attempt", "mistake": "thinking cybersecurity only concerns hackers and experts", "practice": "threat recognition and safety scenarios", "video_terms": "cybersecurity basics phishing malware"},
        "AI": {"overview": "Artificial intelligence allows computers to perform tasks that appear to require human intelligence.", "focus": "pattern recognition, learning from data, and responsible use", "example": "describing how a recommendation system works", "mistake": "assuming AI always understands information like a person", "practice": "AI concept and ethics questions", "video_terms": "artificial intelligence basics machine learning"},
        "Machine Learning": {"overview": "Machine learning is a branch of AI where systems improve using data.", "focus": "training data, patterns, prediction, and models", "example": "using past examples to predict a new outcome", "mistake": "thinking the machine simply memorizes every answer", "practice": "classification and prediction concepts", "video_terms": "machine learning basics models data"},
        "Cloud Computing": {"overview": "Cloud computing delivers computing services over the internet instead of relying only on local machines.", "focus": "storage, servers, accessibility, and service models", "example": "comparing local file storage with cloud storage", "mistake": "thinking the cloud is a physical place with no real servers", "practice": "benefits and risks of cloud services", "video_terms": "cloud computing basics storage services"},
        "Operating Systems": {"overview": "Operating systems manage hardware resources and provide a platform for software.", "focus": "file management, memory, tasks, and user interaction", "example": "explaining how an OS helps run multiple applications", "mistake": "confusing the operating system with application software", "practice": "OS functions and examples", "video_terms": "operating systems basics functions"},
        "Algorithms": {"overview": "Algorithms are logical step-by-step procedures for solving problems.", "focus": "clear instructions, efficiency, and correctness", "example": "writing an algorithm to sort items or search a list", "mistake": "leaving steps ambiguous or unordered", "practice": "algorithm design and tracing", "video_terms": "algorithms basics problem solving"},
        "Data Structures": {"overview": "Data structures organize information so programs can use it efficiently.", "focus": "lists, stacks, queues, trees, and choosing the right structure", "example": "comparing when to use a stack versus a queue", "mistake": "using a structure without understanding its behavior", "practice": "structure identification and use cases", "video_terms": "data structures basics stack queue"},
        "Git": {"overview": "Git helps developers track code changes and collaborate safely.", "focus": "commits, branches, history, and version control workflow", "example": "creating a commit after a code change", "mistake": "editing code without clear commit history", "practice": "basic git workflow concepts", "video_terms": "git basics commits branches"},
        "Software Engineering": {"overview": "Software engineering applies planning, design, testing, and maintenance to build quality software.", "focus": "requirements, design, testing, teamwork, and lifecycle", "example": "moving from problem definition to design and testing", "mistake": "treating coding as the only part of software development", "practice": "development lifecycle and team-role questions", "video_terms": "software engineering basics lifecycle testing"},
    },
}


def get_curated_topic_profile(subject: str, topic: str, overview: str | None = None):
    subject_profiles = TOPIC_PROFILES.get(subject, {})
    profile = subject_profiles.get(topic, {})
    video_channels = SUBJECT_VIDEO_CHANNELS.get(subject, "Khan Academy")

    clean_overview = overview if overview and not overview.startswith("Learn ") else None
    final_overview = clean_overview or profile.get(
        "overview",
        f"{topic} is an important part of {subject}.",
    )
    focus = profile.get("focus", f"the main ideas and methods involved in {topic}")
    example = profile.get("example", f"a simple classroom example involving {topic}")
    mistake = profile.get("mistake", f"treating {topic} as a memorization task instead of understanding it")
    practice = profile.get("practice", f"short questions that build confidence in {topic}")
    video_terms = profile.get("video_terms", f"{topic} lesson")

    return {
        "overview": final_overview,
        "focus": focus,
        "example": example,
        "mistake": mistake,
        "practice": practice,
        "video_query": f"{video_channels} {video_terms}",
    }
